data:
  seed: 42
  classes_per_task: 10
  num_tasks: 10
  data_root: "${hydra:runtime.cwd}/../data"
  num_workers: 4
  batch_size: 128

model:
  input_dim: 3072 #3 * 32x32
  hidden_dim: 100
  output_dim: 10

optimizer:
  lr: 0.01
  weight_decay: 0.0
  k: 10
  max_lanczos_steps: 100
  momentum: 0.0
  dampening: 0.0
  nesterov: False
  calculate_next_top_k: True

training:
  seed: 42
  num_epochs: 2
  log_interval: 10
  subspace_type: "bulk"
  eval_freq: 1
  checkpoint_freq: 1
  device: "cuda:0"
  num_subsamples_Hessian: 5_000

wandb:
  enabled: True
  project: "split_cifar100${training.subspace_type}"

hydra: 
  run:
    dir: "${hydra:runtime.cwd}/../results/split_cifar100/subspace-${training.subspace_type}/k-${optimizer.k}/batch_size-${data.batch_size}/hidden_dim-${model.hidden_dim}/lr-${optimizer.lr}/seed-${training.seed}"

