data:
  seed: 42
  classes_per_task: 2
  num_tasks: 5
  data_root: "${hydra:runtime.cwd}/../data"
  num_workers: 4
  batch_size: 32

model:
  in_channels: 3
  image_size: 32
  hidden_dim: 100
  width: 32

optimizer:
  lr: 0.001
  weight_decay: 0.0
  k: 10
  max_lanczos_steps: 100
  momentum: 0.0
  dampening: 0.0
  nesterov: False
  calculate_next_top_k: True

training:
  seed: 42
  num_epochs: 5
  log_interval: 10
  subspace_type: null
  eval_freq: 1
  checkpoint_freq: 1
  device: "cuda:0"
  num_subsamples_Hessian: 5_000

wandb:
  enabled: True
  project: "split_cifar10${training.subspace_type}"

hydra: 
  run:
    dir: "${hydra:runtime.cwd}/../results/split_cifar10/subspace-${training.subspace_type}/k-${optimizer.k}/batch_size-${data.batch_size}/hidden_dim-${model.hidden_dim}/lr-${optimizer.lr}/seed-${training.seed}"

